"""Classifier configuration constants."""

from manafold.models.classifiers.config.pooling import (
  POOLING_SUM,
  POOLING_MEAN,
  POOLING_QUANTITY_WEIGHTED,
  POOLING_MODES,
  SET_TRANSFORMER_POOLING_PMA,
  SET_TRANSFORMER_POOLING_QUANTITY_WEIGHTED,
  SET_TRANSFORMER_POOLING_HYPERGEOMETRIC,
  SET_TRANSFORMER_POOLING_MODES,
)
from manafold.models.classifiers.config.partial import (
  DEFAULT_PARTIAL_OBSERVATION_IDENTITY_COUNTS,
  DEFAULT_PARTIAL_CLASSIFICATION_WEIGHT,
  DEFAULT_PARTIAL_CONSISTENCY_WEIGHT,
  DEFAULT_PARTIAL_MIN_COVERAGE_WEIGHT,
  DEFAULT_PARTIAL_LATENT_WEIGHT,
  DEFAULT_PARTIAL_TEACHER_DECAY,
  PARTIAL_CORRUPTION_FIXED,
  PARTIAL_CORRUPTION_MIXTURE,
  PARTIAL_CORRUPTION_POLICIES,
)
from manafold.models.classifiers.config.sampling import (
  DEFAULT_HYPERGEOMETRIC_DRAW_COUNT,
  TRAINING_SAMPLING_NATURAL,
  TRAINING_SAMPLING_NATURAL_SQRT_BALANCED,
  TRAINING_SAMPLING_POLICIES,
  DEFAULT_BALANCED_SAMPLING_FRACTION,
  DEFAULT_BALANCED_SAMPLING_MAX_MULTIPLIER,
)
from manafold.models.classifiers.config.architecture import (
  DEEPSETS_ARCHITECTURE_BASE,
  DEEPSETS_ARCHITECTURE_PLUSPLUS,
  DEEPSETS_ARCHITECTURES,
  PROTOTYPE_DISTANCE_EUCLIDEAN,
)

__all__ = [
  # Pooling
  "POOLING_SUM",
  "POOLING_MEAN",
  "POOLING_QUANTITY_WEIGHTED",
  "POOLING_MODES",
  "SET_TRANSFORMER_POOLING_PMA",
  "SET_TRANSFORMER_POOLING_QUANTITY_WEIGHTED",
  "SET_TRANSFORMER_POOLING_HYPERGEOMETRIC",
  "SET_TRANSFORMER_POOLING_MODES",
  # Partial observation
  "DEFAULT_PARTIAL_OBSERVATION_IDENTITY_COUNTS",
  "DEFAULT_PARTIAL_CLASSIFICATION_WEIGHT",
  "DEFAULT_PARTIAL_CONSISTENCY_WEIGHT",
  "DEFAULT_PARTIAL_MIN_COVERAGE_WEIGHT",
  "DEFAULT_PARTIAL_LATENT_WEIGHT",
  "DEFAULT_PARTIAL_TEACHER_DECAY",
  "PARTIAL_CORRUPTION_FIXED",
  "PARTIAL_CORRUPTION_MIXTURE",
  "PARTIAL_CORRUPTION_POLICIES",
  # Sampling
  "DEFAULT_HYPERGEOMETRIC_DRAW_COUNT",
  "TRAINING_SAMPLING_NATURAL",
  "TRAINING_SAMPLING_NATURAL_SQRT_BALANCED",
  "TRAINING_SAMPLING_POLICIES",
  "DEFAULT_BALANCED_SAMPLING_FRACTION",
  "DEFAULT_BALANCED_SAMPLING_MAX_MULTIPLIER",
  # Architecture
  "DEEPSETS_ARCHITECTURE_BASE",
  "DEEPSETS_ARCHITECTURE_PLUSPLUS",
  "DEEPSETS_ARCHITECTURES",
  "PROTOTYPE_DISTANCE_EUCLIDEAN",
]
